Project/website/auth.py
from flask import Blueprint, render_template, request, flash, redirect, url_for
from .models import Booking, User, Movie, Shows, Seats, Upcoming
from werkzeug.security import generate_password_hash, check_password_hash  
from . import db
from flask_login import login_user, login_required, logout_user, current_user
import random
import string
import pyqrcode 


#making a blueprint for flask application called auth
auth = Blueprint('auth',__name__)

@login_required
@auth.route('/admin',methods=['GET','POST'])
def admin():
    return render_template("admin/index.html",a=100)

 
@auth.route('/login',methods=['GET','POST'])
def login():
    if request.method == 'POST':
        email = request.form.get('email')
        password = request.form.get('password')

        user = User.query.filter_by(email=email).first()
        if user:
            if check_password_hash(user.password,password):
                flash('Logged in successfully!',category='success')
                login_user(user, remember=True)
                return redirect(url_for('views.home'))
            else:
                flash('Incorrect password, try again',category='error')
        else:
            flash('Email does not exist',category='error')
    return render_template("login.html", user=current_user)

@auth.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('auth.login'))

@auth.route('/sign_up', methods=['GET','POST'])
def sign_up():
    if request.method == 'POST':
        email = request.form.get('email')
        first_name = request.form.get('firstName')
        password1 = request.form.get('password1')
        password2 = request.form.get('password2')  

        user = User.query.filter_by(email=email).first()
        if user:
            flash('Email already exists',category='error')
        elif len(email) < 4:
            flash('Email must be greater than 3 characters.', category='error')
        elif len(first_name) < 2:
            flash('First name must be greater than 1 character.', category='error')
        elif password1 != password2:
            flash('Passwords don\'t match.', category='error')
        elif len(password1) < 7:
            flash('Password must be at least 7 characters.', category='error')
        else:
            new_user = User(email=email, first_name=first_name, password=generate_password_hash(password1,method='sha256'))
            db.session.add(new_user)
            db.session.commit()
            flash('Account Created!',category='success')
            #login_user(user, remember=True)
            return redirect(url_for('views.home'))


    return render_template("sign_up.html", user=current_user)
        
    
     
@auth.route('/description1',methods=['GET','POST'])
def description():
    
    r = db.session.execute("SELECT * from Movie").fetchall()
    
    a = request.form.get('hello')

    return render_template("description1.html",user=current_user,a=int(a),mov=r)

  
@auth.route('/upcomingmovie',methods=['GET','POST'])
def upcomingmovie():

    r = db.session.execute("SELECT * from Upcoming").fetchall()   

    a = request.form.get('hello')

    return render_template("description2.html",user=current_user,a=int(a),mov=r)



@auth.route('/booking',methods=['GET','POST'])
def booking():
 
   
    movsel = request.form.get("movSel")

    r = db.session.execute("SELECT * from Shows where mov_id="+str(movsel))

    shows = r.fetchall()

    return render_template("booking.html",user=current_user,mov=shows,movsel=movsel)




@auth.route('/seats',methods=['GET','POST'])
def seats():

    
    show_sel  = request.form.get('showsel')

    r = db.session.execute('SELECT * from Seats')
    sho = db.session.execute('SELECT * from Seats where show_id='+str(show_sel))

    
    for i in range(1,101):
        new_booking = Seats(seat_no=i,show_id=int(show_sel))
        db.session.add(new_booking)
    
    #db.session.commit()
    
    
    
    
    seat = r.fetchall()

    show = sho.fetchall()

    seatcount = int(len(show)/2)

    return render_template("seats.html",user=current_user,seats=seat,sh=show,showsel=show_sel,seatcount=seatcount)

@auth.route('/confirmation',methods=['GET','POST'])
@login_required
def confirmation():


    
    li = request.form.getlist('seatList')

    sh = request.form.get('movsel')
    
    newli = request.form.getlist('seatList')
    
    newli.append(sh)
    

    listToStr = ','.join(map(str, newli))

    
    

    movid = str(db.session.execute("SELECT mov_id from Shows where id="+str(sh[0])).fetchall())

    mid =''
    for i in movid:
        if i.isnumeric():
            mid=mid+i


    mt = db.session.execute("SELECT * from Movie where id="+mid).fetchall()

    s = db.session.execute("SELECT * from Shows where id="+sh +" and mov_id="+mid).fetchall()

    r = db.session.execute('SELECT * from Seats').fetchall()

    sho = db.session.execute('SELECT * from Seats where show_id='+str(sh)).fetchall()




    if len(li) <= 10:
        return render_template("confirmation.html",user=current_user,li=li,sh=sh,lilen=len(li),movid=mt,strlist=listToStr,shows=s,m=mid) 
    else:
        flash('Please select less than 10 seats', category='error')
        return render_template("seats.html",user=current_user,seats=r,sh=sho,showsel=sh,seatcount=int(len(sho)/2))


@auth.route('/acknowledgement',methods=['GET','POST'])
def acknowledgement():

    l = request.form.get('confirm')

    user = current_user
    
    showsel = l[-1]

    
    li = request.form.get('confirm')
    
    li = li[:-2]

    li= li.split(',')


    if li:

            new_booking = Booking(user_id=user.id)
            db.session.add(new_booking)
            db.session.commit()
            flash('Booking done!',category='success')
    else:
        flash('Please select a seat',category="error")
    
    a = Booking.query.filter_by(user_id=user.id).all()
    
    a1 = a[len(a)-1]

    bid = a1.id

    u = User.query.filter_by(id=user.id).first()
    uname = u.first_name

    s=''
    if li:
        for i in li:
            a = db.session.execute('SELECT id from Seats where seat_no = '+ i+' and show_id = '+showsel ).fetchall()
            
    s = ','.join(map(str, li)) 
    
    if s:
        for i in li:

                db.session.execute('UPDATE Seats set book_id = '+str(bid)+' where id='+i)
                db.session.execute('UPDATE Seats set status="Booked" where id ='+i)
                db.session.commit()


    movid = str(db.session.execute("SELECT mov_id from Shows where id="+showsel).fetchall())

    mid =''
    for i in movid:
        if i.isnumeric():
            mid=mid+i


    mt = db.session.execute("SELECT * from Movie where id="+mid).fetchall()

    s1 = db.session.execute("SELECT * from Shows where id="+showsel +" and mov_id="+mid).fetchall()

    N = 7
    b =  ''.join(random.choices(string.ascii_uppercase +
                             string.digits, k = N))

    

   
    return render_template("final_page.html",user=current_user,li=li,a=a,showsel=showsel,lilen=len(li),s=s,uname=uname,mov=mt,shows=s1,b=b,bid=bid)



Project/website/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

     <!--CSS----->

     <link rel="stylesheet" type="text/css" href="static/base-styling.css">
     <!--Icons-->
     <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
 
     <!--Font -->
     <link rel="preconnect" href="https://fonts.googleapis.com">
     <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
     <link href="https://fonts.googleapis.com/css2?family=Bangers&family=Staatliches&display=swap" rel="stylesheet"> 

     <!--Bootstrap-->

     <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"    crossorigin="anonymous" />

     <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" crossorigin="anonymous" />
     
     <title>{% block title %}Base{% endblock %}</title>

    </head>


    <body >

       

    <nav>
        <header>
            <ol class="headerstyle">
                <li id="title"><h2><a id="title" href="\">SHOWTIME</a></h2></li>
                

                {% if user.is_authenticated %}
                
                <li class="logout"><a id ="logout" href="\logout">Logout</a></li>
                <li class="logout"><a id ="login">{{user.first_name}}</a></li>

                {% else %}

                <li class="login"><a id ="login" href="\login">LOGIN / SIGN UP</a></li>

                {% endif %}

                <li id="account"><i class="fa fa-user-circle " aria-hidden="true"></i></li>
                <br>
                
                
            </ol>
        </header>
    </nav>

    {% with messages = get_flashed_messages(with_categories = true) %}

    {% if messages %}
      {% for category,message in messages %}
      {% if category=='error' %}
      <div id="flashstyle-error"class="alert alert-danger alter-dismissable fade show" role="alert">
        {{ message }}
        <button type="button" class="close" data-dismiss="alert">
          <span class="close-btn" aria-hidden="=true">&times;</span>
        </button>
      </div>
      {% else  %}
      <div id="flashstyle-success" class="alert alert-success alter-dismissable fade show" role="alert">
        {{ message }}
        <button type="button" class="close" data-dismiss="alert">
          <span  class="close-btn" aria-hidden="=true">&times;</span>
        </button>
      </div>
      {% endif %}
      {% endfor %}
    {% endif %}
    {% endwith %}
   

    

   

   
 
<div class="content">

    

{%block content%}

{% endblock %}


</div>


<!--Bootstrap js-->


<script
src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
crossorigin="anonymous"
></script>
<script
src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
crossorigin="anonymous"
></script>
<script
src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
crossorigin="anonymous"
></script>




 <script
    type="text/javascript"
    src="{{ url_for('static', filename='index.js') }}"
  ></script>
</body>
</html>

Project/website/templates/booking.html
{% extends "base.html" %}
{% block title %}Booking{% endblock %}

{%block content%}

<div class="bookingpage">


<form class="shows-container"action="{{ url_for('auth.seats')}}" method="post"> 

  {% for a in mov %}
  
          <button class="show" name="showsel" type="submit" value={{a[0]}}>

          
           
          
          Theatre : {{ a[1] }} <br> 
          Date : {{ a[2] }} <br>
          Time : {{ a[3] }} &nbsp; &nbsp; Price : &#x20B9;{{ a[5] }}

          

          

          </button> 
  {% endfor %}
  
  </form>

</div>


{% endblock %}

Project/website/templates/confirmation.html
{% extends "base.html" %}
{% block title %}Confirmation{% endblock %}

{%block content%}


<body class="backgroundimage">

    <form  class="loginform " action="{{ url_for('auth.acknowledgement')}}" method="POST" >

    <div class="confirmbox">
    <h3 id="conf">CONFIRM BOOKING DETAILS</h3> <br>

        
    <p class="confhead">Movie:  {{ movid[0][1] }}</p>
    <p class="confhead">Theatre:  {{ shows[0][1] }}</p>
    <p class="confhead">Date :  {{ shows[0][2] }} </p> 
    <p class="confhead">Time : {{ shows[0][3]}} </p> 
    <p class="confhead">Seats : {{ lilen }} &nbsp; &nbsp; Seat no : &nbsp; {{strlist[:-2]}}  </p>
    <p class="confhead">Price : &#x20B9; {{(shows[0][5]*lilen)+(0.18*shows[0][5])}}  </p>     

    <button class="confirmbutton" name= "confirm" type="submit" value={{strlist}}>CONFIRM BOOKING</button>
    
    
    </div>
    </form>

</body>




  





{% endblock %}

Project/website/templates/description1.html
{% extends "base.html" %}
{% block title %}{{mov[a-1][1]}}{% endblock %}
{%block content%}


<form action="{{ url_for('auth.booking')}}"  method="post">

<div class="movie-container">
    <div class="poster">
        <img src="{{ mov[a-1][6] }}" alt="">
    </div>
    <div class="info" style="overflow-y:scroll; height:92vh">
        <div class="movie-title">
            {{mov[a-1][1]}}
        </div>
        <div class="movie-details">
            <div class="set">
                <label >Release Date</label>
                <span class="setstyle">
                    {{mov[a-1][2]}}
                </span>
            </div>
            <div class="set">
                <label>Running Time</label>
                <span class="setstyle">
                    {{mov[a-1][3]}}
                </span>
            </div>
            <div class="set">
                <label>Genre</label>
                <span class="setstyle">
                    
                    {{mov[a-1][4]}}

                </span>
            </div>
        </div>
        <div class="movie-description">

            {{mov[a-1][5]}}
            
        </div>



        <div class="item">

            
            <button class="movie-btn" name="movSel" type="submit" value={{a}}>BOOK NOW  </button>

            

        </div>
        
                </div>
            </div>
        </div>
        
    </div>
</div>

</form>

{% endblock %}

Project/website/templates/description2.html
{% extends "base.html" %}
{% block title %}{{mov[a-1][1]}}{% endblock %}
{%block content%}




<div class="movie-container">
    <div class="poster">
        <img src="{{mov[a-1][6]}}">
    </div>
    <div class="info" style="overflow-y:scroll; height:92vh">
        <div class="movie-title">
            {{mov[a-1][1]}}
        </div>
        <div class="movie-details">
            <div class="set">
                <label>Release Date</label>
                <span>
                    {{mov[a-1][2]}}
                </span>
            </div>
            <div class="set">
                <label>Running Time</label>
                <span>
                    {{mov[a-1][3]}}
                </span>
            </div>
            <div class="set">
                <label>Genre</label>
                <span> {{mov[a-1][4]}} </span>
            </div>
        </div>
            <div class="movie-description">{{mov[a-1][5]}}</div>
    </div>
        </div>
      
        Noo booking button



{% endblock %}

Project/website/templates/final_page.html
{% extends "base.html" %}
{% block title %}Acknowledgement{% endblock %}

{%block content%}


    
        
<body class="backgroundimage">


    
    <div class="t-loginform "  >

        <div class="t-confirmbox">
        
            <div class="t-title">SHOWTIME</div>
            
            <div class="l1-circle"></div>
            <div class="l2-circle"></div>
            <div class="l3-circle"></div>
            <div class="l4-circle"></div>
            <div class="t-box">
                
                
            <img src="{{mov[0][6]}}" class="t-img">
            
            <div class="right-details" > 
            
                
                <h4 class="t-info">{{ mov[0][1] }}</h4>
                <h5 class="t-label">{{ shows[0][1] }}</h5>
                <h5 class="t-label">{{ shows[0][2] }} &nbsp; | &nbsp;  {{ shows[0][3]}}</h5>
                <h5 class="t-label">Booking id : {{ bid }}{{b}}</h5>
                <h5 class="t-label">Price : &#x20B9; </h5>
                <h5 class="t-label">Seats : {{ lilen }} </h5>
            
            
            </div>
            <div class="qr-img"> 
            <img class="qr" src="https://upload.wikimedia.org/wikipedia/commons/thumb/d/d0/QR_code_for_mobile_English_Wikipedia.svg/1200px-QR_code_for_mobile_English_Wikipedia.svg.png">
            </div>

            <h5 class="td-label">Seat no</h5>

            <h1 class="td-info">{{ s  }}</h1>

            <h5 class="td-screen">Screen</h5>

            <h1 class="td-screen-no">{{ shows[0][6] }}</h1>

            </div>
            

        
        </div>
        </div>
    
   
    

{% endblock %}

Project/website/templates/home.html
{% extends "base.html" %}
{% block title %}Home{% endblock %}

{%block content%}




        <!--Carousel-->
    
        <div class="slideshow-container">

            <!-- Full-width images with number and caption text -->
            <div class="mySlides">
            <img class="carousel" src="../static/images/spiderman2.jpg">
            </div>
          
            <div class="mySlides">
            <img class="carousel" src="../static/images/spiderman3.jpeg">
            </div>
          
            <div class="mySlides">
            <img class="carousel" src="../static/images/black_widow_carousel.jpeg">
            </div>
    
            <div class="mySlides">
            <img class="carousel" src="../static/images/black panther.jpg">
            </div>
    
            <div class="mySlides">
            <img class="carousel" src="../static/images/infinity war final.jpg">
            </div>


          
            <!-- Next and previous buttons -->
            <a class="prev" onclick="plusSlides(-1)">&#10094;</a>
            <a class="next" onclick="plusSlides(1)">&#10095;</a>

            <!-- The dots/circles -->
        <div style="text-align:center">
            <span class="dot" onclick="currentSlide(1)"></span>
            <span class="dot" onclick="currentSlide(2)"></span>
            <span class="dot" onclick="currentSlide(3)"></span>
            <span class="dot" onclick="currentSlide(4)"></span>
            <span class="dot" onclick="currentSlide(5)"></span>
         </div>
        
        </div>

        <!--Upcoming Movies list-->
    
        <span class="movie-heading">Upcoming Releases</span>

        <form action="{{ url_for('auth.upcomingmovie')}}" method="post"> 

            {% for a in range(1,mid+1) %}
            
                        
                     <button class="movbutton"name="hello" type="submit" value={{a}}><img class="movie-images-db" src="{{mv[a-1][6]}}">
                    </button>
    
            {% endfor %}
            
            </form>
        

        <span class="movie-heading">Showing Now</span>
        
        <div>

        <form action="{{ url_for('auth.description')}}" method="post"> 

        {% for a in range(1,movid+1) %}
        
                    
                 <button class="movbutton"name="hello" type="submit" value={{a}}><img class="movie-images-db" src="{{  mov[a-1][6]  }} " >
                </button>

                

        {% endfor %}
        
        </form>

        </div>


        

{% endblock %}

Project/website/templates/login.html
{% extends "base.html" %}
{% block title %}Login{% endblock %}
{%block content%}


<body class="backgroundimage">

    <form method="POST" >

    <div class="loginform">
    <h3>LOGIN HERE</h3>

    <label class="labelstyle" for="email">Email Address</label>
    <input class="inputstyle" type="email" class="form-control" id="email" name="email" placeholder="Enter Email">

    <label class="labelstyle" for="password">Password</label>
    <input class="inputstyle" type="password" class="form-control" id="password" name="password" placeholder="Enter Password">
    

    <button class="loginbutton" type="submit">LOG IN</button>
    <div class="social">
     New Here?  <a id="signUp" href="/sign_up">Sign Up</a> now! 
    </div>
    </div>
    </form>

</body>

{% endblock %}

Project/website/templates/seats.html
{% extends "base.html" %}
{% block title %}Seats{% endblock %}

{%block content%}
<div class="seatingstyle">

<form   action="{{ url_for('auth.confirmation')}}" id="reservation" method="post">


<div class="seat-container-left">
{% for a in range(1,(seatcount+1)) %}


  
{%  if sh[a-1][2]=="Booked"  %}

<div class="seat-booked"></div>

{%   else  %}
<div >
<input id="seat-{{a}}" class="seat-select" type="checkbox" value={{a}} name="seatList" />
<label for="seat-{{a}}" class="seat"> {{a}} </label>  

</div>

{% endif %}




{% endfor %}

</div>


<div class="seat-container-right">
    {% for a in range((seatcount)+1,(seatcount*2)+1) %}
    
    
      
    {%  if sh[a-1][2]=="Booked"  %}
    
    <div class="seat-booked"></div>
    
    {%   else  %}
    <div >
    <input id="seat-{{a}}" class="seat-select" type="checkbox" value={{a}} name="seatList" />
    <label for="seat-{{a}}" class="seat"> {{a}} </label>  
    
    </div>
    
    {% endif %}
    
    
    
    
    {% endfor %}
    
    </div>

<span class="seat-button">


<button class="seat-movie-btn" name="movsel" type="submit" value="{{showsel}}">BOOK NOW</button>

</span>
</form>



</div>

{% endblock %}

Project/website/templates/sign_up.html
{% extends "base.html" %}
{% block title %}Sign Up{% endblock %}
{%block content%}

<body class="backgroundimage">
    <form method="POST"  class="loginform" id="signupform">
        <h3>SIGNUP HERE</h3>

        
            <label class="labelstyle" for="email">Email Address</label>
            <input class="inputstyle" type="email" class="form-control" id="email" name="email" placeholder="Enter Email">
        
    
        
            <label  class="labelstyle" for="firstName">First Name</label>
            <input class="inputstyle" type="text" class="form-control" id="firstName" name="firstName" placeholder="Enter First Name">
        
    
        
            <label class="labelstyle" for="password1">Password</label>
            <input class="inputstyle" type="password" class="form-control" id="password1" name="password1" placeholder="Enter Password">
        
    
        
            <label class="labelstyle" for="password2">Confirm Password</label>
            <input class="inputstyle" type="password" class="form-control" id="password2" name="password2" placeholder="Confirm Password">
        
        
        <button type="submit" class="loginbutton">SIGN UP</button>
    </form>
</body>

{% endblock %}